apiVersion: v1
kind: ServiceAccount
metadata:
  name: was-tekton-triggers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: was-tekton-triggers
subjects:
- kind: ServiceAccount
  name: was-tekton-triggers
  namespce: CHANGE_ME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: was-tekton-triggers
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: was-tekton-triggers
rules:
- apiGroups:
      - ''
  resources:
      - secrets
      - configmaps
  verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
- apiGroups:
      - triggers.tekton.dev
  resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - triggers
      - clusterinterceptors
  verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
- apiGroups:
      - tekton.dev
  resources:
      - pipelineruns
      - pipelineresources
      - taskruns
  verbs:
      - create
      - get
      - list
      - delete
      - update
      - watch
- apiGroups:
      - ''
  resources:
      - serviceaccounts
  verbs:
      - impersonate
- apiGroups:
      - policy
  resources:
      - podsecuritypolicies
  verbs:
      - use

