apiVersion: tekton.dev/v1beta1
kind: Task
name: download-ibmcloud-obs
spec:
  params:
     - name: APIKEY
       description: IBM Cloud API Key
       type: string
       default: none
     - name: BUCKET_NAME
       description: bucket name in IBM Cloud OBS 
       type: string
       default: none
     - name: FILE_NAME
       description: name of file download from bucket
       type: string
       default: none
     - name: GROUP_NAME
       description: IBM Cloud Group name to use
       type: string
       default: default
     - name: REGION_NAME
       description: IBM Cloud region
       type: string
       default: us-south

  steps:
     - name: login and download
       image: image-registry.openshift-image-registry.svc:5000/was/ibmcloud-cli:latest
       resources: {}
       script: >
          #!/bin/bash
          IBMCLOUD_API_KEY=${params.APIKEY)
          ibmcloud login -g $(params.GROUP_NAME) -r $(params.REGION_NAME)
          ibmcloud cos object-get --bucket $(params.BUCKET_NAME) --key (params.FILE_NAME) /output/$(params.FILE_NAME)
      
  workspaces:
     - name: output
       description: The bucket file will be downloaded into this dir
       mountPath: /workspace/source
