apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: was-pipeline-obs
spec:
  workspaces:
    - name: shared-workspace

  params:
    - default: ulm
      description: The name of the application
      name: APP_NAME
      type: string
    - default: '1.0'
      description: The version of the application
      name: APP_VERSION
      type: string
    - default: was
      description: The project where you deploy the app
      name: DEPLOY_PROJECT
      type: string
    - default: '2'
      description: max numnber of pods to scale
      name: MAX_PODS
      type: string
    - default: "required"
      description: API Key for IBM Cloud
      name: APIKEY
      type: string 
    - default: "required"
      description: OBS Bucket Name
      name: BUCKET_NAME
      type: string 
    - default: "required"
      description: File name to download and expand
      name: FILE_NAME
      type: string 
    - default: "required"
      description: IBM Cloud group name
      name: GROUP_NAME
      type: string 
    - default: "us-south"
      description: IBM Cloud region
      name: REGION_NAME
      type: string 

  tasks:
    - name: validate-appname
      taskRef:
        name: was-conform-appname
      params:
        - name: APP_NAME
          value: $(params.APP_NAME)

    - name: fetch-repository
      taskRef:
        name: download-ibmcloud-obs
      runAfter:
        - validate-appname
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APIKEY
          value: $(params.APIKEY)
        - name: BUCKET_NAME
          value: $(params.BUCKET_NAME)
        - name: FILE_NAME
          value: $(params.FILE_NAME)
        - name: GROUP_NAME
          value: $(params.GROUP_NAME)
        - name: REGION_NAME
          value: $(params.REGION_NAME)

    - name: build-container-image
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repository
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(params.DEPLOY_PROJECT)/$(tasks.validate-appname.results.APP_NAME_CONFORM):$(params.APP_VERSION)
      workspaces:
        - name: source
          workspace: shared-workspace
     
    - name: deploy-application
      taskRef:
        name: was-deploy-app
      runAfter:
        - build-container-image
      params:
        - name: APP_NAME
          value: $(tasks.validate-appname.results.APP_NAME_CONFORM)
        - name: APP_VERSION
          value: $(params.APP_VERSION)
        - name: DEPLOY_PROJECT
          value: $(params.DEPLOY_PROJECT)
        - name: MAX_PODS
          value: $(params.MAX_PODS)
      workspaces:
        - name: output
          workspace: shared-workspace

  results:
    - name: APP_NAME_CONFORM
      value: $(tasks.validate-appname.results.APP_NAME_CONFORM)
